resources:

  repositories:

  # The name used to reference this repository in the checkout step

  - repository: LeBashCalcRepo 

    type: github

    endpoint: LeChangCS

    name: LeChangCS/bashCalc

# The name used to reference this repository in the checkout step

  - repository: LeWindowsBatchRepo

    type: github

    endpoint: LeChangCS

    name: LeChangCS/winBatch

trigger:
- master

stages:
#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
